### ISSUE TITLE
Deploying straight in a subfolder

### ISSUE THREAD

**Issue by eyan** [gabordemooij/straight#1]
When deploying `straight` in a subfolder, one can edit the `fmap` call in `routes.php` to:
`if (!fmap( [ '/subfolder/' => '' ], '__do' )) {`
to make the whole thing work. 

Leaving this here for those souls who might encounter this same problem.

Might be a good idea to put it in the README as well.

Thank you @gabordemooij  for straight, RedBean and StampTE. I'm using all of them.

**Comment by gabordemooij** [comment]
@eyan thanks for the appreciation! Good to hear some of my projects have proven useful.

I will add your note to the readme.

**Comment by gabordemooij** [comment]
Also added to site: http://gabordemooij.com/straight/

**Comment by gabordemooij** [comment]
Lots of other projects coming by the way...

**Comment by eyan** [comment]
Looking forward!

Closing issue. Thanks again!
