### ISSUE TITLE
Optional sections in slugs?

### ISSUE THREAD

**Issue by eyan** [gabordemooij/straight#2]
Say I have:
```
GET /article/123
__url_get_article( 123 );
```
and I just access `/article/`. Straight gives me an error.

Any way we can leave out `123` and still let `__url_get_article()` handle the request?

**Comment by gabordemooij** [comment]
Hi

Sorry for my late response, I must have missed this one.

Strange though, I cant seem to reproduce this error:

function __do_get_article($a) {
	die("Artikel $a");
}


/* Handle requests */
if (!fmap( [ '/web/straight/public_html'=>''], '__do' )) { //working from subfolder here but should make no difference,...
	/* No request handler has been found... */
	http_response_code(404);
	die('wut?');
}

../article/9 --> Artikel 9
../article/ --> Artikel
../article --> Artikel

??

**Comment by eyan** [comment]
Hi,

Thank you for getting back to me.

When I access `/sample` or `/sample/` defined as `function __do_get_sample($x)`:

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function __do_get_sample(), 0 passed in D:\binxampp\htdocs\xxx\src\lib\Straight\straight.php on line 94 and exactly 1 expected in D:\binxampp\htdocs\xxx\src\app\controller\sample.php:93

Not a big problem, really. Was just wondering if there's a simple solution.

Closing this and will dig some more. Problem might be on my side.

Again, thank you.

**Comment by gabordemooij** [comment]
What happens if you use:

`function __do_get_sample($x = null){ `:

?

**Comment by eyan** [comment]
No error! 💃 Woohoo!

Thank you! Sorry I didn't think of that myself.

**Comment by gabordemooij** [comment]
you're welcome!
