### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by alystair** [gabordemooij/straight#3]
Although this framework is _straight_ forward compared to others, it would be cool to have a basic diagram of the code flow for a page request utilizing all features (i18n, config) so it's stupid easy to comprehend at a glance when initially going through the doc.

browser request -> fmap -> ??? -> rendered page

**Comment by gabordemooij** [comment]
Sounds good, might be useful indeed...

**Comment by gabordemooij** [comment]
Would you mind creating this diagram? I have tried to make a diagram but I don't know what features you like to include. The diagrams that I created are either way too complicated or way too simplistic. Clearly, you have a nice picture in mind, so maybe you could draw something?

**Comment by gabordemooij** [comment]
Ok done
https://gabordemooij.com/straight/
